name: OmniPackage agent on Github actions
description: Runs single-shot agent triggered by OmniPackage

runs:
  using: "composite"
  steps:
    - name: Install Ruby and Podman
      shell: bash
      run: |
        set -euo pipefail
        sudo apt-get update
        sudo apt-get install -y ruby-full podman
        ruby -v
        podman --version

    - name: Run agent
      shell: bash
      run: |
        set -euo pipefail

        if [ -z "${APIKEY:-}" ]; then
          echo "APIKEY is not set"
          exit 1
        fi

        cat > config.yml <<EOF
apikey: <%= ::ENV.fetch('APIKEY') %>
apihost: 'https://web.omnipackage.org'
image_cache_enable: false
container_limits_disable: true
single_shot: true
single_shot_wait_sec: 200
EOF

        exe/omnipackage-agent -c config.yml
