extract_version:
  provider: 'file'
  file:
    file: 'lib/omnipackage_agent/version.rb'
    regex: "VERSION = '(.+)'"

rpm: &rpm
  installable_package_name: 'omnipackage-agent'
  build_dependencies: []
  runtime_dependencies: ['ruby', 'tar', 'xz']
  rpm:
    spec_template: '.omnipackage/specfile.spec.liquid'

deb: &deb
  installable_package_name: 'omnipackage-agent'
  build_dependencies: []
  runtime_dependencies: ['ruby', 'tar', 'xz']
  deb:
    debian_templates: '.omnipackage/deb'

builds:
- distro: 'opensuse_15.3'
  <<: *rpm

- distro: 'opensuse_15.4'
  <<: *rpm

- distro: 'opensuse_15.5'
  <<: *rpm

- distro: 'opensuse_15.6'
  <<: *rpm

- distro: 'opensuse_tumbleweed'
  <<: *rpm

- distro: 'fedora_38'
  <<: *rpm

- distro: 'fedora_39'
  <<: *rpm

- distro: 'fedora_40'
  <<: *rpm

- distro: 'fedora_41'
  <<: *rpm

- distro: 'fedora_rawhide'
  <<: *rpm

- distro: 'debian_10'
  <<: *deb

- distro: 'debian_11'
  <<: *deb

- distro: 'debian_12'
  <<: *deb

- distro: 'debian_testing'
  <<: *deb

- distro: 'debian_unstable'
  <<: *deb

- distro: 'ubuntu_20.04'
  <<: *deb

- distro: 'ubuntu_22.04'
  <<: *deb

- distro: 'ubuntu_24.04'
  <<: *deb

- distro: 'almalinux_8'
  <<: *rpm

- distro: 'almalinux_9'
  <<: *rpm

- distro: 'rockylinux_8'
  <<: *rpm

- distro: 'rockylinux_9'
  <<: *rpm

- distro: 'mageia_8'
  <<: *rpm

- distro: 'mageia_9'
  <<: *rpm

- distro: 'mageia_cauldron'
  <<: *rpm
