#!/usr/bin/env ruby
# frozen_string_literal: true

$LOAD_PATH.unshift ::File.expand_path('../lib', __dir__)

require 'optparse'

require 'omnipackage_agent'

options = {}
optparser = ::OptionParser.new do |parser|
  parser.banner = "Usage: #{$PROGRAM_NAME} [options]"

  parser.on('--version', 'show version') do
    puts ::OmnipackageAgent::VERSION
    exit
  end
  parser.on('--help', 'show help info') do
    puts parser
    exit
  end
  parser.on('--[no-]headless', 'run agent without cloud connection')
  parser.on('--source SOURCE_PATH', 'path to source code in headless mode')
  parser.on('--apihost API_HOST', 'cloud api host url')
  parser.on('--apikey API_KEY', 'cloud api key')
  parser.on('--config CONFIG_FILE', 'path to config file')
end
optparser.parse!(into: options)

# pp options
# Dir.chdir(__dir__)

begin
  ::OmnipackageAgent.config = ::OmnipackageOmnipackageAgent::Config.load!(options[:config], options) if options[:config]
  ::OmnipackageAgent.run(options)
rescue ::StandardError => e
  warn e.backtrace
  warn optparser
  exit(1)
end
