#!/usr/bin/env ruby
# frozen_string_literal: true

$LOAD_PATH.unshift ::File.expand_path('../lib', __dir__)

begin
  require 'super_awesome_print'
rescue ::LoadError
end

require 'optparse'

require 'omnipackage_agent'

options = {}
optparser = ::OptionParser.new do |parser|
  parser.banner = "Usage: #{$PROGRAM_NAME} [options]"

  parser.on('-v', '--version', 'show version') do
    puts ::OmnipackageAgent::VERSION
    exit
  end
  parser.on('-h', '--help', 'show help info') do
    puts parser
    exit
  end
  parser.on('--apihost API_HOST', 'cloud api host url')
  parser.on('--apikey API_KEY', 'cloud api key')
  parser.on('-c', '--config CONFIG_FILE', 'path to config file')
end
optparser.parse!(into: options)

# pp options
# Dir.chdir(__dir__)

# ::Signal.trap('HUP') do
#   warn 'caught SIGHUP'
# end

begin
  ::OmnipackageAgent.check_system_packages!
  config = ::OmnipackageAgent::Config.get(options)
  ::OmnipackageAgent.run(config)
rescue ::StandardError => e
  warn "#{e.class}: #{e.message}"
  warn e.backtrace
  warn ''
  warn optparser
  exit(1)
rescue ::Interrupt
  warn 'quitting...'
  exit(0)
end
